#ifndef TEIR_COMPILER_H
#define TEIR_COMPILER_H

#include <memory>

#include "teir.h"
#include "Kernel.h"
#include "InstGen.h"
#include "Unary.h"
#include "Gemm.h"
#include "UnaryCache.h"




struct teir_compiler {
    private:
        /** 
         * The registers which may be used to hold the loop indices.
         * The compiler raises an error if no more registers are available.
         */
        std::vector<mini_jit::InstGen::gpr_t> const loop_registers {
            mini_jit::InstGen::gpr_t::x19,
            mini_jit::InstGen::gpr_t::x20,
            mini_jit::InstGen::gpr_t::x21,
            mini_jit::InstGen::gpr_t::x22,
            mini_jit::InstGen::gpr_t::x23,
            mini_jit::InstGen::gpr_t::x24,
            mini_jit::InstGen::gpr_t::x25,
            mini_jit::InstGen::gpr_t::x26,
        };

        /**
         * Stores the `Unary` instances holding the kernels for the unary primitives.
         */
        UnaryCache unary_cache;

        /**
         * An array of function pointers which may be used by the lowered primitives.
         * This usually contains the function pointers generated by `Unary` and `Gemm`.
         * 
         * The i'th primitive defined by the operation may use the slot `kernel_functions[i]`
         * to store any pointer to a kernel it might need.
         * 
         * A pointer to the array of function pointers is available to the primitives
         * in register `x27`. Use the `blr` instruction to execute a given function.
         */
        std::vector<void*> kernel_functions;

        /**
         * The kernel holding the compiled instructions.
         */
        mini_jit::Kernel kernel;

        /** An instruction generator. */
        mini_jit::InstGen ig;











        /**
         * Converts each tensor id stored in `primitive` to it's index into the tensor pointer array.
         * @param operation: The operation which defines the tensor identifiers.
         * @param primitive: The primitive which holds tensor labels.
         * @return An array of tensor indices.
         */
        std::vector<uint64_t> resolve_tensor_labels(teir_operation const& operation, teir_primitive const& primitive) const;

        /**
         * @brief The signature of a function which attempts to lower a given primitive to assembly code.
         *
         * A function of this signature accepts a primitive defined by the operation and attempts
         * to generate assembly code to execute the primitive.
         *
         * The generated code segment must conform to the default ABI; caller- and callee-saved registers
         * must be handled properly.
         * 
         * The enclosing loop passes a pointer to the tensor pointers in `x28`
         * and `kernel_functions.data()` in `x27`.
         * Strides and offsets are applied to the tensor pointers by the enclosing loop.
         * The enclosing loop expects no return value from the code segment.
         * 
         * @param operation: The operation currently being compiled.
         * @param primitive: The primitive to lower.
         */
        using lower_func_t = bool(teir_compiler::*)(teir_operation const&, teir_primitive const&);

        /** Conforms to `lower_func_t`. */
        bool lower_zero_scalar(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_zero_tile(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_identity_scalar(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_identity_tile_notrans(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_identity_tile_trans(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_relu_scalar(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_relu_tile_notrans(teir_operation const& operation, teir_primitive const& primitive);
        /** Conforms to `lower_func_t`. */
        bool lower_relu_tile_trans(teir_operation const& operation, teir_primitive const& primitive);

        /**
         * @brief Recursively iterates over the schedule nodes to generate the loop nest.
         * @param operation: The operation to compile.
         * @param node: The current node.
         * @param axis_path: The axes iterated over up to but not including the current node.
         * @param index_path: The registers holding the loop indices for the axes in `axis_path`.
         */
        void iterate(teir_operation const& operation, std::string const& node, std::vector<teir_axis const*> axis_path, std::vector<mini_jit::InstGen::gpr_t> index_path);
        /**
         * @brief Lowers the primitive invoked by the invocation node.
         * @param operation: The operation to compile.
         * @param inv_node: The invocation node whose primitive is to be lowered.
         * @param axis_path: The axes iterated over up to but not including the current node.
         * @param index_path: The registers holding the loop indices for the axes in `axis_path`.
         */
        void invoke(teir_operation const& operation, teir_inv_node const* inv_node, std::vector<teir_axis const*> axis_path, std::vector<mini_jit::InstGen::gpr_t> index_path);





        /** The label which may be used to access the shape data. */
        std::string const shape_data_label = "shape_data";

        /**
         * @brief Appends the extends, strides and offsets of the axes to the executable memory of the kernel.
         * @param operation: The operation definining the axes and tensors.
         */
        void append_shape_data(teir_operation const& operation);
        /**
         * @brief Obtains an offset which may be added to the resolved `shape_data_label` to access the extend for the axis.
         * @param operation: The operation defining the axes and tensors.
         * @param axis_id: The ID of the axis for which to obtain the offset.
         * @return An offset to the extend of `axis_id`.
         */
        int32_t get_offset_for_extend(teir_operation const& operation, std::string const& axis_id);
        /**
         * @brief Obtains an offset which may be added to the resolved `shape_data_label` to access the stride for the axis and tensor.
         * @param operation: The operation defining the axes and tensors.
         * @param axis_id: The ID of the axis for which to obtain the offset.
         * @param tensor_id: The ID of the tensor for which to obtain the offset.
         * @return An offset to the stride of the tensor `tensor_id` of the axis `axis_id`.
         */
        int32_t get_offset_for_stride(teir_operation const& operation, std::string const& axis_id, std::string const& tensor_id);
        /**
         * @brief Obtains an offset which may be added to the resolved `shape_data_label` to access the offset-data for the axis and tensor.
         * @param operation: The operation defining the axes and tensors.
         * @param axis_id: The ID of the axis for which to obtain the offset.
         * @param tensor_id: The ID of the tensor for which to obtain the offset.
         * @return An offset to the offset-data of the tensor `tensor_id` of the axis `axis_id`.
         */
        int32_t get_offset_for_offset(teir_operation const& operation, std::string const& axis_id, std::string const& tensor_id);





    public:

        /** 
         * @brief Write a sequence of instruction words into memory to execute the given operation.
         * @param operation: The operation to compile.
         */
        void compile(teir_operation const& operation);


        /**
         * @brief The signature of the compiled function which executes the operation.
         * @param tensors: A pointer to an array of pointers to the tensor memory areas.
         */
        using teir_function_t = void(*)(void**);

        /**
         * @brief Obtain a function pointer which executes the last compiled operation.
         * 
         * The function pointer is only valid for the lifetime of the `teir_compiler` instance which compiled it.
         * 
         * @return The function pointer
         */
        teir_function_t get_function() const;


        /**
         * @brief Writes the instruction words to a file.
         * @param fp: The file path.
         */
        void write(const char* fp) const;
};

#endif