#ifndef TEIR_TEIR_COMPILER_H
#define TEIR_TEIR_COMPILER_H

#include <memory>

#include "teir.h"
#include "Kernel.h"
#include "InstGen.h"
#include "Unary.h"
#include "Gemm.h"
#include "UnaryCache.h"
#include "GemmCache.h"
#include "teir_lowering.h"




struct teir_compiler {
    private:
        /**
         * The registers which may be used to hold the loop indices.
         * The compiler raises an error if no more registers are available.
         */
        std::vector<mini_jit::InstGen::gpr_t> const loop_registers {
            mini_jit::InstGen::gpr_t::x19,
            mini_jit::InstGen::gpr_t::x20,
            mini_jit::InstGen::gpr_t::x21,
            mini_jit::InstGen::gpr_t::x22,
            mini_jit::InstGen::gpr_t::x23,
            mini_jit::InstGen::gpr_t::x24,
            mini_jit::InstGen::gpr_t::x25,
            mini_jit::InstGen::gpr_t::x26,
        };

        /** The maximum number of tensors of an operation containing parallel iteration nodes. */
        static constexpr uint64_t max_parallel_tensors = 16;

        /**
         * Stores the `Unary` instances holding the kernels for the unary primitives.
         */
        UnaryCache unary_cache;

        /**
         * Stores the `Gemm` instances holding the kernels for the contraction primitives.
         */
        GemmCache gemm_cache;

        /**
         * The tile kernel plan of each primitive, indexed like `operation.primitives`.
         */
        std::vector<teir_tile_plan> plans;

        /**
         * An array of function pointers which may be used by the lowered primitives.
         * This usually contains the function pointers generated by `Unary` and `Gemm`.
         *
         * The i'th primitive defined by the operation may use the slot `kernel_functions[i]`
         * to store any pointer to a kernel it might need.
         *
         * A pointer to the array of function pointers is available to the primitives
         * in register `x27`. Use the `blr` instruction to execute a given function.
         */
        std::vector<void*> kernel_functions;

        /**
         * @brief A parallel iteration node, possibly collapsed with directly nested parallel iteration nodes.
         *
         * The loop body is compiled into a separate function `body`, which is executed by
         * `parallel_for` for every iteration using OpenMP threads.
         */
        struct parallel_region {
            /**
             * The signature of the loop body.
             * @param tensors: The tensor pointers, with the offsets and strides of the region's axes applied.
             * @param loop_indices: The values of the loop index registers of the enclosing loops, followed by those of the region's axes.
             */
            using body_t = void(*)(void** tensors, uint64_t const* loop_indices);

            body_t body = nullptr;
            /** The number of enclosing loops. */
            uint64_t depth = 0;
            uint64_t num_tensors = 0;
            /** The extents of the collapsed axes, outermost first. */
            std::vector<uint64_t> extents;
            /** The strides and offsets of the collapsed axes in bytes: `strides[axis * num_tensors + tensor]`. */
            std::vector<int64_t> strides;
            std::vector<int64_t> offsets;
        };

        /** The parallel regions of the compiled operation. The generated code holds pointers to them. */
        std::vector<std::unique_ptr<parallel_region>> regions;

        /** The kernels holding the loop bodies of the parallel regions. */
        std::vector<std::unique_ptr<mini_jit::Kernel>> body_kernels;

        /**
         * @brief Executes all iterations of `region` using OpenMP threads.
         *
         * Called by the generated code. Nested calls, i.e. calls from inside another parallel region, are executed sequentially.
         *
         * @param region: The parallel region.
         * @param tensors: The tensor pointers of the enclosing loop nest.
         * @param loop_indices: The values of the loop index registers of the enclosing loops.
         */
        static void parallel_for(parallel_region const* region, void** tensors, uint64_t const* loop_indices);

        /**
         * The kernel holding the compiled function which executes the operation.
         */
        mini_jit::Kernel main_kernel;

        /**
         * The kernel instructions are currently appended to.
         * This is either `main_kernel` or the body of a parallel region.
         */
        mini_jit::Kernel* kernel = &main_kernel;

        /** An instruction generator. */
        mini_jit::InstGen ig;











        /**
         * Converts each tensor id stored in `primitive` to it's index into the tensor pointer array.
         * @param operation: The operation which defines the tensor identifiers.
         * @param primitive: The primitive which holds tensor labels.
         * @return An array of tensor indices.
         */
        std::vector<uint64_t> resolve_tensor_labels(teir_operation const& operation, teir_primitive const& primitive) const;

        /**
         * @brief Attempts to lower a given primitive to assembly code.
         *
         * The generated code segment must conform to the default ABI; caller- and callee-saved registers
         * must be handled properly.
         *
         * The enclosing loop passes a pointer to the tensor pointers in `x28`
         * and `kernel_functions.data()` in `x27`.
         * Strides and offsets are applied to the tensor pointers by the enclosing loop.
         * The enclosing loop expects no return value from the code segment.
         *
         * @param operation: The operation currently being compiled.
         * @param primitive: The primitive to lower.
         * @return `true` if code was generated, `false` if the lowering does not support the primitive.
         */
        bool lower_zero_scalar(teir_operation const& operation, teir_primitive const& primitive);
        bool lower_identity_scalar(teir_operation const& operation, teir_primitive const& primitive);
        bool lower_relu_scalar(teir_operation const& operation, teir_primitive const& primitive);
        /** Lowers a primitive to a call of the `Unary` or `Gemm` kernel stored in its dispatch table slot. */
        bool lower_tile(teir_operation const& operation, teir_primitive const& primitive);

        /**
         * @brief Recursively iterates over the schedule nodes to generate the loop nest.
         * @param operation: The operation to compile.
         * @param node: The current node.
         * @param axis_path: The axes iterated over up to but not including the current node.
         * @param index_path: The registers holding the loop indices for the axes in `axis_path`.
         */
        void iterate(teir_operation const& operation, std::string const& node, std::vector<teir_axis const*> axis_path, std::vector<mini_jit::InstGen::gpr_t> index_path);
        /**
         * @brief Generates a parallel region for the parallel iteration node `iter_node`.
         *
         * Directly nested parallel iteration nodes without guards are collapsed into the region.
         * The children of the innermost collapsed node are compiled into a separate body function,
         * the current kernel calls `parallel_for` to execute it.
         */
        void iterate_parallel(teir_operation const& operation, teir_iter_node const* iter_node, std::vector<teir_axis const*> const& axis_path, std::vector<mini_jit::InstGen::gpr_t> const& index_path);
        /**
         * @brief Lowers the primitive invoked by the invocation node.
         * @param operation: The operation to compile.
         * @param inv_node: The invocation node whose primitive is to be lowered.
         * @param axis_path: The axes iterated over up to but not including the current node.
         * @param index_path: The registers holding the loop indices for the axes in `axis_path`.
         */
        void invoke(teir_operation const& operation, teir_inv_node const* inv_node, std::vector<teir_axis const*> axis_path, std::vector<mini_jit::InstGen::gpr_t> index_path);


        /** Appends the function prologue saving the frame, link and callee-saved registers x19 to x28 and d8 to d15. */
        void append_prologue();
        /** Appends the function epilogue restoring the registers saved by `append_prologue` and returning. */
        void append_epilogue();
        /** Appends instructions which move the 64-bit value `value` into `reg`. */
        void append_mov_imm64(mini_jit::InstGen::gpr_t reg, uint64_t value);


        /** The label which may be used to access the shape data. */
        std::string const shape_data_label = "shape_data";

        /**
         * @brief Appends the extends, strides and offsets of the axes to the executable memory of the kernel.
         * @param operation: The operation definining the axes and tensors.
         */
        void append_shape_data(teir_operation const& operation);
        /**
         * @brief Obtains an offset which may be added to the resolved `shape_data_label` to access the extend for the axis.
         * @param operation: The operation defining the axes and tensors.
         * @param axis_id: The ID of the axis for which to obtain the offset.
         * @return An offset to the extend of `axis_id`.
         */
        int32_t get_offset_for_extend(teir_operation const& operation, std::string const& axis_id);
        /**
         * @brief Obtains an offset which may be added to the resolved `shape_data_label` to access the stride for the axis and tensor.
         * @param operation: The operation defining the axes and tensors.
         * @param axis_id: The ID of the axis for which to obtain the offset.
         * @param tensor_id: The ID of the tensor for which to obtain the offset.
         * @return An offset to the stride of the tensor `tensor_id` of the axis `axis_id`.
         */
        int32_t get_offset_for_stride(teir_operation const& operation, std::string const& axis_id, std::string const& tensor_id);
        /**
         * @brief Obtains an offset which may be added to the resolved `shape_data_label` to access the offset-data for the axis and tensor.
         * @param operation: The operation defining the axes and tensors.
         * @param axis_id: The ID of the axis for which to obtain the offset.
         * @param tensor_id: The ID of the tensor for which to obtain the offset.
         * @return An offset to the offset-data of the tensor `tensor_id` of the axis `axis_id`.
         */
        int32_t get_offset_for_offset(teir_operation const& operation, std::string const& axis_id, std::string const& tensor_id);




        /**
         * @brief Appends a code segment that branches to `label` if the guard is not satisfied.
         *
         * The code segment must respect caller- and callee-saved registers.
         *
         * @param operation: The operation being compiled.
         * @param axis: The axis corresponding to guard.
         * @param index_path: The register holding the iteration index for `axis`.
         * @param guard: The guard to check.
         * @param label: The label to branch to.
         */
        void append_branch_if_not_guard(teir_operation const& operation, teir_axis const& axis, mini_jit::InstGen::gpr_t axis_reg, teir_guard const& guard, std::string label);
        /**
         * @brief Appends a code segment that branches to `label` if the guard is not satisfied.
         *
         * The code segment must respect caller- and callee-saved registers.
         *
         * @param operation: The operation being compiled.
         * @param axis_path: The ancestor axes of the node containing the guards.
         * @param index_path: The registers holding the iteration indices for each of the axes in `axis_path`.
         * @param guard: The guard to check.
         * @param label: The label to branch to.
         */
        void append_branch_if_not_guard(teir_operation const& operation, std::vector<teir_axis const*> const& axis_path, std::vector<mini_jit::InstGen::gpr_t> const& index_path, teir_guard const& guard, std::string const& label);
        /**
         * @brief Appends a code segment that branches to `label` if the any of the guards is not satisfied.
         *
         * The code segment must respect caller- and callee-saved registers.
         *
         * @param operation: The operation being compiled.
         * @param axis_path: The ancestor axes of the node containing the guards.
         * @param index_path: The registers holding the iteration indices for each of the axes in `axis_path`.
         * @param guards: The guards to check.
         * @param label: The label to branch to.
         */
        void append_branch_if_not_guards(teir_operation const& operation, std::vector<teir_axis const*> const& axis_path, std::vector<mini_jit::InstGen::gpr_t> const& index_path, std::vector<teir_guard> const& guards, std::string const& label);



    public:
        teir_compiler() = default;
        // the generated code holds pointers into the compiler's members
        teir_compiler(teir_compiler const&) = delete;
        teir_compiler& operator=(teir_compiler const&) = delete;

        /**
         * @brief Write a sequence of instruction words into memory to execute the given operation.
         *
         * Each `teir_compiler` instance compiles a single operation.
         * Throws `std::runtime_error` if the operation can not be compiled.
         *
         * @param operation: The operation to compile.
         */
        void compile(teir_operation const& operation);


        /**
         * @brief The signature of the compiled function which executes the operation.
         * @param tensors: A pointer to an array of pointers to the tensor memory areas.
         */
        using teir_function_t = void(*)(void**);

        /**
         * @brief Obtain a function pointer which executes the last compiled operation.
         *
         * The function pointer is only valid for the lifetime of the `teir_compiler` instance which compiled it.
         *
         * @return The function pointer
         */
        teir_function_t get_function() const;


        /**
         * @brief Writes the instruction words to a file.
         * @param fp: The file path.
         */
        void write(const char* fp) const;
};

#endif
