name: SME Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install qemu-user qemu-user-static

    - name: make
      run: |
        cd sme/src/
        make clean TOOLCHAIN=standard
        make all TOOLCHAIN=standard
    
    - name: run
      run: |
        qemu-aarch64-static -cpu max,sve=off,sme=on identity_driver

